site:
  title: GraphQL Demo
  url: http://localhost:8080/graphql-demo
  robots: disallow
urls:
  html_extension_style: drop
asciidoc:
  attributes:
    "page-pagination": "@"
  extensions:
    - "@asciidoctor/tabs"
antora:
  extensions:
    - require: "@antora/lunr-extension"
      languages: [en]
    - require: "@antora-tools/graphql"
      name: graphql-demo
      title: GraphQL Demo
      intro: |
        Welcome to the `GraphQL Demo` pages. Feel free to take a look around!

        IMPORTANT: These pages are for demo purposes only.
      display_version: 0.5.9
      strategy: INTROSPECTION
      location: https://spacex-production.up.railway.app
      api_endpoint: https://spacex-production.up.railway.app
ui:
  bundle:
    url: ui-bundle.zip
