site:
  title: Antora docs
  robots: disallow
urls:
  html_extension_style: drop
asciidoc:
  attributes:
    "page-pagination": "@"
  extensions:
    - "@asciidoctor/tabs"
antora:
  extensions:
    - require: "@antora/lunr-extension"
      languages: [en]
    - require: "@antora-tools/graphql"
      name: graphql-demo
      title: GraphQL Demo
      strategy: INTROSPECTION
      api_endpoint: https://spacex-production.up.railway.app
      location: https://spacex-production.up.railway.app
ui:
  bundle:
    url: ui-bundle.zip
    # url: https://github.com/aerogear/antora-ui/raw/master/build/ui-bundle.zip
    # snapshot: true
