site:
  title: Antora docs
  start_page: docs::index.adoc
  robots: disallow
urls:
  html_extension_style: drop
asciidoc:
  attributes:
    page-pagination: "@"
  extensions:
    - "@asciidoctor/tabs"
antora:
  extensions:
    - require: "@antora/lunr-extension"
      languages: [en]
    - require: "@antora-tools/graphql"
      enable_logging: true
      component:
        name: graphql-demo
        title: GraphQL Demo
        version: 0.0.1
        asciidoc:
          "page-pagination": ""
      introspection:
        api_endpoint: https://spacex-production.up.railway.app
        strategy: REMOTE
        location: https://spacex-production.up.railway.app
content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: ui-bundle.zip
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
