site:
  title: Antora docs
  start_page: docs::index.adoc
urls:
  html_extension_style: drop
antora:
  extensions:
    - require: "@antora/lunr-extension"
      languages: [en]
content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
