site:
  title: GraphQL Demo
  url: https://markopostma.github.io/antora-docs/graphql-demo
  robots: disallow
urls:
  html_extension_style: drop
asciidoc:
  attributes:
    page-pagination: "@"
  extensions:
    - "@asciidoctor/tabs"
antora:
  extensions:
    - require: "@antora/lunr-extension"
      languages: [en]
    - require: "@antora-tools/graphql"
      name: graphql-demo
      title: GraphQL Demo
      display_version: 0.5.2
      strategy: INTROSPECTION
      location: https://spacex-production.up.railway.app
      api_endpoint: https://spacex-production.up.railway.app
ui:
  bundle:
    url: ui-bundle.zip
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
