site:
  title: Antora docs
  url: /site
  start_page: antora-tools-graphql::index.adoc
  robots: disallow
urls:
  html_extension_style: drop
asciidoc:
  attributes:
    "page-pagination": "@"
  extensions:
    - "@asciidoctor/tabs"
antora:
  extensions:
    - require: "@antora/lunr-extension"
      languages: [en]
    - require: "@antora-tools/graphql"
      name: graphql-demo
      title: GraphQL Demo
      display_version: 0.8.1
      intro: |
        Welcome to the `GraphQL Demo` pages. Feel free to take a look around!

        IMPORTANT: These pages are for demo purposes only.
      strategy: INTROSPECTION
      location: https://spacex-production.up.railway.app
      api_endpoint: https://spacex-production.up.railway.app
content:
  sources:
    - url: .
      start_path: docs
      branches: [HEAD]
ui:
  bundle:
    url: ui-bundle.zip
