site:
  title: Antora docs
  start_page: docs::index.adoc
  robots: disallow
  url: https://markopostma.github.io/antora-docs
urls:
  html_extension_style: drop
asciidoc:
  attributes:
    page-pagination: "@"
  extensions:
    - "@asciidoctor/tabs"
antora:
  extensions:
    - require: "@antora/lunr-extension"
      languages: [en]
    - require: "@antora-tools/graphql"
      name: graphql-demo
      title: GraphQL Demo
      display_version: 0.4.2
      strategy: INTROSPECTION
      location: https://spacex-production.up.railway.app
      api_endpoint: https://spacex-production.up.railway.app
content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: ui-bundle.zip
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
