site:
  title: Antora docs
  url: /antora-docs
  start_page: antora-docs::index.adoc
  robots: disallow
urls:
  html_extension_style: drop
asciidoc:
  attributes:
    page-pagination: "@"
  extensions:
    - "@asciidoctor/tabs"
antora:
  extensions:
    - require: "@antora/lunr-extension"
      languages: [en]
    - require: "@antora-tools/graphql"
      name: graphql-demo
      title: Documentation Demo
      display_version: 0.9.0
      intro: |
        Welcome to the **Documentation Demo** 📚 pages.
        In front of you are static pages generated in `Antora` by using the `@antora-tools/graphql` extension!

        [TIP,caption="Api-endpoint"]
        ====
        `https://spacex-production.up.railway.app`
        ====
      strategy: INTROSPECTION
      location: https://spacex-production.up.railway.app
content:
  sources:
    - url: .
      start_path: docs
      branches: [HEAD]
ui:
  bundle:
    url: ui-bundle.zip
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
