site:
  title: Antora docs
  start_page: docs::index.adoc
  robots: disallow
urls:
  html_extension_style: drop
asciidoc:
  extensions:
    - "@asciidoctor/tabs"
antora:
  extensions:
    - require: "@antora/lunr-extension"
      languages: [en]
content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: ui-bundle.zip
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
